<a href="https://colab.research.google.com/github/TejaswiReddySandi/deep-learning-assignments/blob/main/DL_2_Tensorflowbasicoperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
a = tf.constant([3,4,5,6])
print(a)

tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)


creates a constant tensor from a tensor like object

In [ ]:
b = tf.constant([11,12,13,14])
print(b)

tf.Tensor([11 12 13 14], shape=(4,), dtype=int32)


Basic math operations:
*   add(x,y,name=none)
*   subtract(x,y,name=none)
*   mul(x,y,name=none)
*   List item
*   List item





div(x,y,name=none)
add_n(inputs,name=none)
mod()
scalar_mul(scalar,x)
abs(x,name=none)
negative(x,name=none)
sin(x,name=none)
reciprocal(x,name=none)

In [ ]:
c = tf.math.add_n([a,b])
print(c)

tf.Tensor([14 16 18 20], shape=(4,), dtype=int32)


In [ ]:
sum = tf.add(a,b)
print(sum)  

tf.Tensor([14 16 18 20], shape=(4,), dtype=int32)


In [ ]:
diff = tf.subtract(a,b)
print(diff)

tf.Tensor([-8 -8 -8 -8], shape=(4,), dtype=int32)


In [ ]:
total = a + b
print(total)

tf.Tensor([14 16 18 20], shape=(4,), dtype=int32)


In [ ]:
div = a/b
print(div)

tf.Tensor([0.27272727 0.33333333 0.38461538 0.42857143], shape=(4,), dtype=float64)


In [ ]:
a = tf.constant([[2,1],[4,5]])
print(a)
b = tf.constant([[11,1],[22,6]])
print(b)

tf.Tensor(
[[2 1]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[11  1]
 [22  6]], shape=(2, 2), dtype=int32)


In [ ]:
ss = tf.add_n([a,b])
print(ss)

tf.Tensor(
[[13  2]
 [26 11]], shape=(2, 2), dtype=int32)


In [ ]:
from tensorflow.python.ops.math_ops import scalar_mul

from numpy import dtype

#initialising input sensor
scalar = (5)
x = tf.constant([2.5,4.23,-546.5,43.5],dtype=tf.float64)
print(scalar)
print(x)
c = scalar_mul(scalar,x)
print(c)

5
tf.Tensor([  2.5    4.23 546.5   43.5 ], shape=(4,), dtype=float64)
tf.Tensor([  12.5    21.15 2732.5   217.5 ], shape=(4,), dtype=float64)


In [ ]:
print(abs(x))

tf.Tensor([  2.5    4.23 546.5   43.5 ], shape=(4,), dtype=float64)


In [ ]:
x = tf.constant([-3,2,-5,23],dtype=tf.float64)
print(tf.math.negative(x))

tf.Tensor([  3.  -2.   5. -23.], shape=(4,), dtype=float64)


In [ ]:
print(tf.math.sin(x))

tf.Tensor([-0.14112001  0.90929743  0.95892427 -0.8462204 ], shape=(4,), dtype=float64)


In [ ]:
#computes the reciprocal
a =  tf.constant([-0.5,-1,0.5,1.5])
print(tf.math.reciprocal(a,name='reciprocal'))

tf.Tensor([-2.        -1.         2.         0.6666667], shape=(4,), dtype=float32)


**23/02/2022**

In [ ]:
#initialising tf constant
#
a = tf.zeros(7)
print(a)
b = tf.zeros((7,2))
print(b)
c = tf.zeros((3,2,2))
print(c)

tf.Tensor([0. 0. 0. 0. 0. 0. 0.], shape=(7,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(7, 2), dtype=float32)
tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], shape=(3, 2, 2), dtype=float32)


In [ ]:
a = tf.ones(5)
print(a)
b = tf.ones((2,5))
print(b)
c = tf.ones((3,2,5))
print(c)

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 2, 5), dtype=float32)


In [ ]:
#filling tensors with arbitary values using fill()
b = tf.fill((2,2),value=5)
print(b)

tf.Tensor(
[[5 5]
 [5 5]], shape=(2, 2), dtype=int32)


In [ ]:
#creating a constant tensor
const = tf.constant([12,7,6,2])
const

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12,  7,  6,  2], dtype=int32)>

In [ ]:
a = tf.random.normal((2,2),mean=0,stddev=1)
print(a)
b = tf.random.uniform((5,5),minval=-2,maxval=2)
b

tf.Tensor(
[[ 0.02020629  0.32226014]
 [-1.5317972  -1.5279696 ]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.9354525 ,  1.9406247 , -0.31233406,  0.75430346,  1.0566783 ],
       [-1.8615012 ,  1.2810073 , -0.3934846 ,  1.4412026 , -0.02247763],
       [ 0.83253145,  0.7428479 , -1.9682307 ,  0.88833666,  1.6408887 ],
       [ 1.9410338 ,  1.7745571 , -1.5016856 , -1.6908021 ,  0.28726435],
       [ 0.8806915 ,  1.0697474 , -0.23709774, -0.23921585,  1.7509251 ]],
      dtype=float32)>

In [ ]:
#creating an identity matrix
a = tf.eye(4)
print(a)

#printing a diagonal matrix using range(start,limit,delta or stepsize)
b = tf.range(1,7,1)
print(b)
d = tf.linalg.diag(b)
print(d)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]], shape=(6, 6), dtype=int32)


In [ ]:
#matrix transpose
a = tf.ones((2,3))
print(a)
b = tf.transpose(a)
print(b)
#matrix multiplication
c = tf.matmul(a,b)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)


InvalidArgumentError: ignored

In [ ]:
#Eusing fill()
a = tf.fill((2,3),value=5)
b = tf.fill((3,2),value=5)
#c = tf.matmul(a,b)
print(c)

tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)


In [ ]:
a = tf.ones(8)
d = tf.reshape(a,(4,2))
print(d)
d = tf.reshape(a,(2,2,2))
print(d)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [ ]:
#getting the shape of tensor
b = a.get_shape()
print(b)

(8,)
